# (generated with --quick)

from typing import Any

logging: module
np: module
plt: module

def create_patch(X, ps = ...) -> Any: ...
def enable_cloud_log(level = ...) -> None: ...
def plot_images(name, X_test, Y_pred, Y_true) -> None: ...
def plot_imgpair(Y_pred, Y_true, name) -> None: ...
def plot_loss(fpath, history) -> None: ...
